pull_request_rules:
- actions:
    merge:
      method: merge
      rebase_fallback: merge
  conditions:
  - -base=automerge
  - label!=no-mergify
  - '#approved-reviews-by>=1'
  - "status-success=test"
  name: default
- actions:
    merge:
      method: merge
      rebase_fallback: merge
  conditions:
  - base=automerge
  - label!=no-mergify
  - "status-success=test"
  name: automerge branch
- name: check for authorization
  conditions:
    - author!=@dev
  actions:
    post_check:
      title: |
        {% if check_succeed %}
        Pull request authorized
        {% else %}
        Pull request unauthorized
        {% endif %}
      summary: |
        {% if not check_succeed %}
        You are not authorized to create a pull request because you are not a
        member of the dev team.
        {% endif %}
- name: check for fixes
  conditions:
    - "title~=^(fix|feat|docs|style|refactor|perf|test|build|ci|chore|revert)(?:\\(.+\\))?:"
  actions:
    post_check:
      title: |
        {% if check_succeed %}
        Title follows Conventional Commit
        {% else %}
        Title does not follow Conventional Commit
        {% endif %}
      summary: |
        {% if not check_succeed %}
        Your pull request title must follow [Conventional Commit](https://www.conventionalcommits.org/en/v1.0.0/).
        {% endif %}
