pull_request_rules:
  - name: automatic merge
    conditions:
      - author=@devs
      - label=automerge
      - status-success=test
    actions:
      merge:
        method: merge
        rebase_fallback: merge
        
  - name: add label on javascript pr
    conditions:
      - files~=javascript
    actions:
      label:
        add:
          - javascript

  - name: assign PRs with Python files modified to sileht
    conditions:
      - files~=\.py$
      - -closed
    actions:
      assign:
        add_users:
          - another-jd

  - name: clean branches
    conditions: []
    actions:
      delete_head_branch:
