pull_request_rules:
- actions:
    merge:
      method: merge
      rebase_fallback: merge
  conditions:
  - -base=automerge
  - label!=no-mergify
  - '#approved-reviews-by>=1'
  - "status-success=test"
  name: default
- actions:
    merge:
      method: merge
      rebase_fallback: merge
  conditions:
  - base=automerge
  - label!=no-mergify
  - "status-success=test"
  name: automerge branch
- name: check for authorization
  conditions:
    - author!=@dev
  actions:
    post_check:
      title: |
        {% if check_succeed %}
        Pull request authorized
        {% else %}
        Pull request unauthorized
        {% endif %}
      summary: |
        {% if not check_succeed %}
        You are not authorized to create a pull request because you are not a
        member of the dev team.
        {% endif %}
- name: check for fixes
  conditions:
    - label=bug
    - -body~=(?m)^Fixes MYPROJECT-
  actions:
    post_check:
      title: |
        {% if check_succeed %}
        Bug identifier found
        {% else %}
        No bug identifier
        {% endif %}
      summary: |
        {% if not check_succeed %}
        You need to specify a link to a bug identifier, such as `Fixes
        MYPROJECT-42` in your pull request.
        {% endif %}
