pull_request_rules:
- name: default
  actions:
    merge:
      method: merge
      rebase_fallback: merge
  conditions:
  - -base=automerge
  - label!=no-mergify
  - '#approved-reviews-by>=1'
  - status-success=continuous-integration/travis-ci
- name: automerge branch
 actions:
    merge:
      method: merge
      rebase_fallback: merge
  conditions:
  - base=automerge
  - label!=no-mergify
  - status-success=continuous-integration/travis-ci
