pull_request_rules:
- actions:
    merge:
      method: merge
      rebase_fallback: merge
  conditions:
  - -base=automerge
  - label!=no-mergify
  - '#approved-reviews-by>=1'
  - "status-success=ci/circleci: test"
  name: default
- actions:
    merge:
      method: merge
      rebase_fallback: merge
  conditions:
  - base=automerge
  - label!=no-mergify
  - "status-success=ci/circleci: test"
  name: automerge branch
