rules:
  default:
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 1
      required_status_checks:
        contexts:
          - continuous-integration/travis-ci
  automerge:
    protection:
      required_pull_request_reviews:
        required_approving_review_count: 0
      required_status_checks:
        contexts:
          - continuous-integration/travis-ci
