pull_request_rules:
- actions:
    merge:
      method: merge
      rebase_fallback: merge
  conditions:
  - -base=automerge
  - label!=no-mergify
  - '#approved-reviews-by>=1'
  - "status-success=test"
  name: default
- actions:
    merge:
      method: merge
      rebase_fallback: merge
  conditions:
  - base=automerge
  - label!=no-mergify
  - "status-success=test"
  name: automerge branch
- name: check for authorization
  conditions:
    - author!=@dev
  actions:
    post_check:
      title: |
        {% if check_succeed %}
        Pull request authorized
        {% else %}
        Pull request unauthorized
        {% endif %}
      summary: |
        {% if not check_succeed %}
        You are not authorized to create a pull request because you are not a
        member of the dev group
        {% endif %}
- name: check for labels
  conditions:
    - label=feature
    - label=bug
  actions:
    post_check:
      title: |
        {% if not check_succeed %}
        Labels are correct
        {% else %}
        Too many labels
        {% endif %}
      summary: |
        {% if not check_succeed %}
        Feature and Bug labels cannot be used at the same time.
        {% endif %}
