version: 2.1

jobs:
  test:
    docker:
      - image: circleci/python:3.7
    steps:
      - checkout
      - run:
          command: sleep 60

workflows:
  version: 2

  test:
    jobs:
      - test

