name: Continuous Integration
on:
  pull_request:
    branches:
      - master
  pull_request_target:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-20.04
    steps:
      - uses: actions/checkout@v2
      - run: |
          sleep 60
